"""setup

Revision ID: 43feae3a7823
Revises: 
Create Date: 2022-07-11 20:09:40.581550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43feae3a7823'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
